# Generated by Django 4.0.1 on 2022-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre de Producto')),
                ('Precio', models.IntegerField(max_length=50, verbose_name='Precio')),
                ('Cantidad', models.IntegerField(max_length=50, verbose_name='Cantidad')),
            ],
        ),
    ]
