# Generated by Django 4.0.1 on 2022-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='Cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='Precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
