# Generated by Django 4.0.1 on 2022-06-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carrito_cantidad_alter_carrito_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='Cantidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='Precio',
            new_name='precio',
        ),
    ]
