# Generated by Django 4.0.5 on 2022-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cantidad_carrito_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maceteros'),
        ),
    ]
